---
# tasks file for roles/webapps
- name: create directories
  file:
    path: /usr/share/tomcat/webapps/ansible
    state: directory

- name: copy index.html to tomcat
  template:
    src: index.html.j2
    dest: /usr/share/tomcat/webapps/ansible/index.html 
